include:
  - project: KOF/pipeline-templates
    ref: main
    file: stages.yml
.renv_variables: &renv_vars
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library

.renv: &renv
  variables:
    <<: *renv_vars
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - ${RENV_PATHS_LIBRARY}

  before_script:
    - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
    - Rscript -e "renv::restore()"

coverage:
  <<: *renv
  image: core.harbor.kof.ethz.ch/library/kofdocker/kofrenv:latest
  stage: check
  coverage: '/Coverage: \d+\.\d+/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  variables:
    <<: *renv_vars
  script:
    - R -e "renv::install(c('testthat', 'covr'))"
    - R -e "{coverage_report <- covr::package_coverage(quiet = FALSE);
             print(coverage_report);
             covr::to_cobertura(coverage_report, filename = 'coverage.xml')}"
  rules:
    - exists:
        - renv.lock
