on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  RENV_PATHS_ROOT: ~/.cache/R/renv

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          brew install gfortran # if needed for Fortran dependencies

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Restore renv
        uses: r-lib/actions/setup-renv@v2

      - name: Build the source package
        run: |
          R CMD build .

      - name: Install and build macOS binary
        run: |
          R CMD INSTALL --build *.tar.gz
        shell: bash

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: "*.tgz"
